import logging
logging.basicConfig(
    format="%(asctime)s - %(levelname)s - %(name)s -   %(message)s",
    datefmt="%m/%d/%Y %H:%M:%S",
    level=logging.INFO,
)

import spacy

from src.detector import LMAbbreviationDetector


text = "The 2002–3 pandemic caused by severe acute respiratory syndrome coronavirus (SARS-CoV) was one of the most significant public health events in recent history(1). An ongoing outbreak of Middle East respiratory syndrome coronavirus (MERS-CoV)(2) suggests that this group of viruses remains a major threat and that their distribution is wider than previously recognized. Although bats have been suggested as the natural reservoirs of both viruses(3–5), attempts to isolate the progenitor virus of SARS-CoV from bats have been unsuccessful. Diverse SARS-like coronaviruses (SL-CoVs) have now been reported from bats in China, Europe and Africa(5–8), but none are considered a direct progenitor of SARS-CoV because of their phylogenetic disparity from this virus and the inability of their spike proteins (S) to use the SARS-CoV cellular receptor molecule, the human angiotensin converting enzyme II (ACE2)(9,10). Here, we report whole genome sequences of two novel bat CoVs from Chinese horseshoe bats (Family: Rhinolophidae) in Yunnan, China; RsSHC014 and Rs3367. These viruses are far more closely related to SARS-CoV than any previously identified bat CoVs, particularly in the receptor binding domain (RDB) of the S protein. Most importantly, we report the first recorded isolation of a live SL-CoV (bat SL-CoV-WIV1) from bat fecal samples in Vero E6 cells, which has typical coronavirus morphology, 99.9% sequence identity to Rs3367 and uses the ACE2s from human, civet and Chinese horseshoe bat for cell entry. Preliminary in vitro testing indicates that WIV1 also has a broad species tropism. Our results provide the strongest evidence to date that Chinese horseshoe bats are natural reservoirs of SARS-CoV, and that intermediate hosts may not be necessary for direct human infection by some bat SL-CoVs. They also highlight the importance of pathogen discovery programs targeting high-risk wildlife groups in emerging disease hotspots as a strategy for pandemic preparedness."
text = '''Carnitine, carnitine acetyltransferase, and glutathione in Alzheimer brain. Glutathione and &quot;total&quot; carnitine (i.e., free carnitine plus acid-soluble carnitine esters) were measured in an affected (superior frontal gyrus; SFG) and unaffected (cerebellum: CBL) region of Alzheimer disease (AD) and control brains. Average glutathione content in AD SFG (n = 13) and AD CBL (n = 7) (7.9 +/- 2.1 and 11.9 +/- 4.0 nmol/mg protein, respectively (mean +/- S.D.)) was similar to that in control SFG (n = 13) and CBL (n = 6) (7.7 +/- 2.0 and 11.6 +/- 2.6 nmol/mg protein, respectively). However, glutathione increased significantly with age in AD brain (p = 0.003) but not in control brain. Average total carnitine in AD SFG (84 +/- 47 pmol/mg protein; n = 10) and AD CBL (108 +/- 86 pmol/mg protein; n = 7) was not significantly different from that in the corresponding regions of control brain (148 +/- 97 (n = 10) and 144 +/- 107 (n = 6) pmol/mg protein, respectively). However, a significant decline of total carnitine with age in both regions was noted for AD brain, but not for control brain. Carnitine acetyltransferase activity in the AD SFG (n = 13) was not significantly different from that of control SFG (n = 13) (1.83 +/- 1.05 and 2.04 +/- 0.82 nmol/min/mg protein, respectively). However, carnitine acetyltransferase activity of AD CBL (n = 7) was significantly lower than that of control CBL (n = 6) (1.33 +/- 0.88 versus 2.26 +/- 0.66 nmol/min/mg protein; p = 0.05).'''
text = '''Survival determinants in lung transplant patients with chronic allograft dysfunction. BACKGROUND: Chronic lung allograft dysfunction (CLAD) remains the leading cause of mortality after lung transplantation. METHODS: In this retrospective single-center study, we aimed to identify different phenotypes of and risk factors for mortality after CLAD diagnosis using univariate and multivariate Cox proportional hazard survival regression analysis. RESULTS: CLAD was diagnosed in 71 of 294 patients (24.2%) at 30.9±22.8 months after transplantation. Pulmonary function was obstructive in 51 (71.8%) of the CLAD patients, restrictive in 20 (28.2%) patients, of whom 17 had persistent parenchymal infiltrates on pulmonary computer tomography (CAT) scan. In univariate analysis, previous development of neutrophilic reversible allograft dysfunction (NRAD, P=0.012) and a restrictive pulmonary function (P=0.0024) were associated with a worse survival, whereas there was a strong trend for early development of CLAD and persistent parenchymal infiltrates on CAT scan (P=0.067 and 0.056, respectively). In multivariate analysis, early development of CLAD (P=0.0067), previous development of NRAD (P=0.0016), and a restrictive pulmonary function pattern (P=0.0005) or persistent parenchymal infiltrates on CAT scan (P=0.0043) remained significant. CONCLUSION: Although most CLAD patients develop an obstructive pulmonary function, 28% develop a restrictive pulmonary function, compatible with the recently defined restrictive allograft syndrome phenotype. Early-onset CLAD, previous development of NRAD, and the development of restrictive allograft syndrome are associated with worse survival after CLAD has been diagnosed.'''
nlp = spacy.load('en_core_sci_sm')
nlp.add_pipe('lm_abbreviation_detector', config={'config_path': 'models/config.json', 'tokenizer_path': 'allenai/scibert_scivocab_cased', 'model_path': 'models/abbreviation_detector_v2.pt'})
doc = nlp(text)
for x in doc._.abbreviations:
    print(x['short_form'])

print()
for x in doc._.abbreviation_pairs:
    print(f'{x["short_form"]}: {x["long_form"]}')

abbr_detector = nlp.get_pipe('lm_abbreviation_detector')
print(abbr_detector.pipe(text))